### PR TITLE
Add new EnvironmentFile source: /etc/default/mdns-reflector.d/*

### LINKED ISSUE #3: Debian upload?
Hey is something planned regarding a Debian Upload?

Maybe we want to use this program in our own project (Debian Edu Router).
A quick response would be appreciated since there is hope that we can make it into Debian 12 before its freeze.

I've tested this software on Debian Bookworm and it works.

### PR DESCRIPTION
**Pull request by dzatoah**
Allows us to have multiple coexisting config files. Files are read in alphanumerical order.

`99_*` has a higher priority as `00_*` files.

Debian packaging files can be found here:
https://salsa.debian.org/debian-edu-pkg-team/mdns-reflector

Fixes: #3

cc: @sunweaver

### CODE REVIEW

**Comment by vfreex** [comment]
Hi, thanks for the PR. A quick question: will there be a problem if we keep the debian directory here for local testing?

**Comment by sunweaver** [comment]
@dzatoah @vfreex IMHO, there is no real reason for removing the debian/ folder. @dzatoah please update this MR so the debian/ folder stays in. (@dzatoah is working in my company).

**Comment by dzatoah** [comment]
Done!

**Review by vfreex — APPROVED** [review]
/lgtm

**Pull request merged**
